### ISSUE TITLE
Support for offset angle

### ISSUE THREAD

**Issue by davidmuzi** [tadija/AEConicalGradient#1]
Could you add support for setting the starting angle for the GradientLayer?

I got this to work by adding an offset to the `angle` property in `drawRect` before calling `colorForAngle`

**Comment by scottpgreen1972** [comment]
I can't even get it to build!

installed correctly with cocoa pods, but when I do a test build in Xcode I get compiler errors. Does anyone have a working version of this? Would be so happy if I could get this up and running.

**Comment by tadija** [comment]
Hi @scottpgreen1972, it's not yet completely updated for Swift 3, but at least build should work from develop branch (master is still old version).

**Comment by scottpgreen1972** [comment]
Hi tadija! brilliant work by the way, really love it!  just wish it would compile!  I'm using the develop branch in Xcode beta 2 and I'm getting 12 errors. Looking through them, a few are to do with outdated syntax, so probably no major problem - but the one that really stops it appears to be a 'method does not override any method from its superclass' error on the public override class func layerClass() in AEConicalGradientView.swift.  I am a complete noob at this, so apologies if I am missing something completely obvious, but I just don't know what to do!  Any help you could give would be massively appreciated!

Scott

**Comment by tadija** [comment]
Hi @davidmuzi, thanks for suggestion, I've added `startAngle` and `endAngle` properties in 2.0.0.

@scottpgreen1972 try new version, it's just published now.

**Comment by scottpgreen1972** [comment]
Brilliant!

Got it working now.  Really excellent work. How can I alter the size of the layer?  I don;t want the gradient to fill the whole screen

**Comment by davidmuzi** [comment]
Thanks, @tadija Ill give it a try.

@scottpgreen1972 can you please create a new issue and continue your discussion there? Lets keep this issue on topic.

**Comment by scottpgreen1972** [comment]
Sure thing David.

I’m very new to Github, so apologies while I feel my way around.
