### ISSUE TITLE
startAngle/endAngle Behavior

### ISSUE THREAD

**Issue by chulbert** [tadija/AEConicalGradient#3]
I would expect the color at location 0.0 to begin at startAngle and the color at 1.0 to end at endAngle; however, it appears colors are unconditionally distributed from 0 to 2pi and startAngle/endAngle simply clip the drawing.  For example,

gradientView.gradient.colors = [UIColor.red, UIColor.yellow, UIColor.green]
gradientView.gradient.startAngle = .pi
gradientView.gradient.endAngle = 2 * .pi

I would expect this to draw red-yellow-green across the top half of the view.  However, it draws only yellow-green across the top half.

**Comment by tadija** [comment]
Perhaps you're right about angles / locations, but it's already possible to get red-yellow-green across the top half of the view if locations are configured like this: 
`gradientView.gradient.locations = [0.5, 0.75, 1.0]`

![screen shot 2018-09-27 at 23 16 26](https://user-images.githubusercontent.com/2762374/46230760-db1ea080-c369-11e8-913f-2ff71625d580.jpg)
